docs:
  - changed-files:
    - any-glob-to-any-file: 
      - '**/*.md'
      - '**/*.mdx'

styles:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.css'
      - '**/*.scss'
      - '**/*.module.css'
      - '**/*.tailwind.*'

test:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.test.*'
      - '**/*.spec.*'
      - '**/__tests__/**'

ci:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/**'

config:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.json'
      - '**/*.env*'
      - 'tsconfig.*'
      - 'next.config.*'

feature:
  - head-branch: ['^feature']

bug:
  - head-branch: ['^fix', '^bug']

perf:
  - head-branch: ['^perf']

chore:
  - head-branch: ['^chore']

deps:
  - head-branch: ['^deps', '^upgrade']

wip:
  - head-branch: ['^wip']

hotfix:
  - head-branch: ['^hotfix']

release:
  - base-branch: 'main'