docs:
  - changed-files:
    - all-globs-to-all-files: 
      - '**/*.md'
      - '**/*.mdc'
      - '**/*.mdx'

styles:
  - changed-files:
    - all-globs-to-all-files:
      - '**/*.css'
      - '**/*.scss'
      - '**/*.module.css'
      - '**/*.tailwind.*'

test:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.test.*'
      - '**/*.spec.*'
      - '**/__tests__/**'

ci:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/**'

config:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.json'
      - '**/*.env*'
      - 'tsconfig.*'
      - 'next.config.*'

ui:
  - changed-files:
    - any-glob-to-any-file:
      - 'components/**'
      - 'src/components/**'

app-router:
  - changed-files:
    - any-glob-to-any-file:
      - 'app/**'
      - 'src/app/**'

feature:
  - all:
    - head-branch: ['^feature', '^feat']
    - changed-files:
      - any-glob-to-any-file:
        - 'src/**'
        - 'app/**'

bug:
  - all:
    - head-branch: ['^fix', '^bug']
    - changed-files:
      - any-glob-to-any-file:
        - 'src/**'
        - 'app/**'

perf:
  - head-branch: ['^perf']

chore:
  - head-branch: ['^chore']

deps:
  - all:
    - head-branch: ['^deps', '^upgrade']
    - changed-files:
      - any-glob-to-any-file:
        - 'package.json'
        - 'package-lock.json'
        - 'yarn.lock'

wip:
  - head-branch: ['^wip']

hotfix:
  - head-branch: ['^hotfix']

release:
  - all:
    - base-branch: 'main'
    - changed-files:
        - any-glob-to-any-file:
          - 'CHANGELOG.md'